/**
 * App Status Scenarios
 */
export enum Status {
  LOADING_IMAGE = 'LOADING_IMAGE',
  DISPLAY_ORIGINAL = 'DISPLAY_ORIGINAL',
  PLAYING_GAME  = 'PLAYING_GAME',
  FINISHED_GAME = 'FINISHED_GAME',
  ERROR = 'ERROR',
}
